### ISSUE TITLE
Fork error

### ISSUE THREAD

**Issue by pavelloz** [enjalot/building-blocks#81]
What i did:

1) I opened a block
2) I forked block (as anonymous)
3) I edited block
4) I logged in
5) I edited block
6) I tried to fork as logged in user
7) I gave authorization access at github to read my gists
8) It redirected me back to building blocks

Aftrer some time of [loading](https://www.dropbox.com/s/q0i5lwsd8ryy9tk/Screenshot%202015-11-26%2016.20.29.png?dl=0)
i  checked the devtools and see that request `http://blockbuilder.org/auth/github/callback?code=08e8da156f791069aede` returned:
```
InternalOAuthError: failed to fetch user profile
   at /home/ubuntu/Code/building-blocks/node_modules/passport-github/lib/passport-github/strategy.js:90:28
   at passBackControl (/home/ubuntu/Code/building-blocks/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (/home/ubuntu/Code/building-blocks/node_modules/passport-github/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:142:7)
   at IncomingMessage.emit (events.js:129:20)
   at _stream_readable.js:908:16
   at process._tickCallback (node.js:355:11)
```

I see that request for `fork` was made with request parameters: 
```
"{"id":"164a15f8bc71421da38b","description":"block wall: filter user","public":true,"files":{"README.md":{"filename":"README.md","type":"text/plain","language":"Markdown","raw_url":"https://gist.githubusercontent.com/anonymous/164a15f8bc71421da38b/raw/a4e4386126ea792afec54db875f45d3ac6a01a5d/README.md","size":1354,"truncated":false,"content":"A collection of blocks scanned with [blockscanner](https://github.com/iros/blockscanner) for the [bl.ocksplorer.org](http://bl.ocksplorer.org/) project and further processed with [block-similarity](https://github.com/enjalot/block-similarity).\n\n### Try filtering by some usernames\nmbostock, enjalot, syntagmatic, emeeks, nitaku\n\nIf you don't see any of your blocks here, [add your GitHub username](https://docs.google.com/forms/d/1VdDdycNuqJVw3Ik6-ZLj6v7X9g2vWlw_RCC3RCfD9-I/viewform) \nIf you need to add thumbnails to your bl.ocks, use [blockbuilder.org](http://blockbuilder.org)\n\n\nforked from <a href='http://bl.ocks.org/enjalot/'>enjalot</a>'s block: <a href='http://bl.ocks.org/enjalot/6ac67b0d8ed673c9aa61'>all the blocks</a>\n\nforked from <a href='http://bl.ocks.org/enjalot/'>enjalot</a>'s block: <a href='http://bl.ocks.org/enjalot/1d679f0322174b65d032'>block wall</a>\n\nforked from <a href='http://bl.ocks.org/enjalot/'>enjalot</a>'s block: <a href='http://bl.ocks.org/enjalot/211bd42857358a60a936'>block wall: thumbnails only</a>\n\nforked from <a href='http://bl.ocks.org/enjalot/'>enjalot</a>'s block: <a href='http://bl.ocks.org/enjalot/7b63fef8ccfbad1f851e'>block wall: filter user</a>\n\nforked from <a href='http://bl.ocks.org/enjalot/'>enjalot</a>'s block: <a href='http://bl.ocks.org/enjalot/64dbd9b7b740ba44462f'>block wall: filter user</a>"},"blocks.json":null,"fisheye.js":null,"hilbert.js":null,"index.html":{"filename":"index.html","type":"text/html","language":null,"raw_url":"https://gist.githubusercontent.com/anonymous/164a15f8bc71421da38b/raw/962e7589c87d6c4d043dd1594ca96f551691efc0/index.html","size":3884,"truncated":false,"content":"<!DOCTYPE html>\n <head>\n <meta charset=\"utf-8\">\n\n \n <style>\n body { \n margin:0;position:absolute;top:0;right:0;bottom:0;left:0; \n background-color: #111;\n overflow:none;\n }\n #blocks {\n position: absolute;\n top: 40px;\n left: 10px; \n }\n .block {\n position:absolute;\n width: 9px;\n height: 7px;\n text-decoration: none;\n line-height: 9px;\n }\n .block a {\n text-decoration: none;\n }\n #user {\n position: absolute;\n top: 10px;\n left: 10px;\n width: 200px;\n }\n #hover {\n color: white;\n font-size: 11px;\n font-family: Courier new;\n float:right;\n margin: 5px;\n }\n \n \n </style>\n </head>\n\n <body>\n <input id=\"user\" placeholder=\"GitHub username\">\n <div id=\"hover\"></div>\n <div id=\"blocks\">\n </div>\n <script>\n \n </script>\n </body>\n "}}}"
```

The response was status 400 and:
```
{"error":"{\"message\":\"Invalid request.\\n\\nFor 'additionalProperties', nil is not an object.\\nFor 'additionalProperties', nil is not an object.\\nFor 'additionalProperties', nil is not an object.\",\"documentation_url\":\"https://developer.github.com/v3/gists/#create-a-gist\"}"}
```

I tried forking it as logged in user with adblock turned off, no difference.

Anonymous block that i tried to fork as logged in user: http://blockbuilder.org/anonymous/164a15f8bc71421da38b

OS: OSX, browser: Chrome

**Comment by enjalot** [comment]
This seems to happen consistently if you fork a block after having deleted files from it. I have some ideas on how to fix this and I will report back soon. thanks!
